import { Router } from "express";
import authRouter from "../modules/auth/auth.router.js";
import userRouter from "../modules/user/user.router.js";
import jobRouter from "../modules/job/job.router.js";
import quoteRouter from "../modules/quote/quote.router.js";
import vehicleRouter from "../modules/vehicle/vehicle.router.js";
import fleetRouter from "../modules/fleet/fleet.router.js";
import billingRouter from "../modules/billing/billing.router.js";
import invoiceRouter from "../modules/invoice/invoice.router.js";
import earningRouter from "../modules/earning/earning.router.js";
import notificationRouter from "../modules/notification/notification.router.js";
import supportTicketRouter from "../modules/supportTicket/supportTicket.router.js";
import adminRouter from "../modules/admin/admin.router.js";
import reviewRouter from "../modules/review/review.router.js";
import disputeRouter from "../modules/dispute/dispute.router.js";
import chatRouter from "../modules/chat/chat.router.js";
import companyRouter from "../modules/company/company.router.js";
import feedPresetRouter from "../modules/feedPreset/feedPreset.router.js";
import mediaRouter from "../modules/media/media.router.js";

const router = Router();

router.use("/auth", authRouter);
router.use("/users", userRouter);
router.use("/jobs", jobRouter);
router.use("/quotes", quoteRouter);
router.use("/fleet/vehicles", vehicleRouter);
router.use("/fleet", fleetRouter);
router.use("/billing", billingRouter);
router.use("/invoices", invoiceRouter);
router.use("/earnings", earningRouter);
router.use("/notifications", notificationRouter);
router.use("/support/tickets", supportTicketRouter);
router.use("/fleet/reviews", reviewRouter);
router.use("/fleet/disputes", disputeRouter);
router.use("/chat", chatRouter);
router.use("/admin", adminRouter);
router.use("/company", companyRouter);
router.use("/feed-presets", feedPresetRouter);
router.use("/media", mediaRouter);

export default router;
